# This is a basic workflow that is manually triggered

name: CI REACT

on:
  push:
    branches:
    - master

jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - name: Pull code
        run: git pull origin master
      - name: Install library
        run: yarn install
      - name: Build app
        run: yarn build
